version: '3'
services:
  db:
    image: mysql:latest
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
    - db_data:/var/lib/mysql
    - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - "3306:3306"
  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD: password
    depends_on:
      - db

volumes:
  db_data: